name    'counsyl-vbox'
version '0.9.1'
source  'git://github.counsyl.com/dev/puppet-vbox.git'
author  'Counsyl, Inc.'
license 'Apache License, Version 2.0'
summary 'Puppet module for installing and configuring VirtualBox'
description 'Puppet module for installing and configuring VirtualBox'
project_page 'https://github.counsyl.com/dev/puppet-vbox'

dependency 'counsyl/sys', '>= 0.9.0'
dependency 'counsyl/apt', '>= 0.9.0'
